INSERT INTO marca (nome_marca, id_pais) VALUES
('Lattafa Perfumes', 57),
('Jean Paul Gaultier', 69),
('By Kilian', 69),
('Xerjoff', 93),
('Maison Francis Kurkdjian', 69),
('Yves Saint Laurent', 69),
('Maison Martin Margiela', 69),
('Dior', 69),
('Giorgio Armani', 93),
('Tom Ford', 63),
('Versace', 93),
('Chanel', 69),
('Parfums de Marly', 69),
('Viktor&Rolf', 135),
('Burberry', 146),
('Afnan', 57),
('Giardini Di Toscana', 93),
('Armaf', 57),
('Dolce&Gabbana', 93),
('Creed', 69),
('Carolina Herrera', 189);