INSERT INTO acorde (nome_acorde) VALUES
    ('Especiado Quente'),
    ('Baunilha'),
    ('Especiado Fresco'),
    ('Aromático'),
    ('Verde'),
    ('Âmbar'),
    ('Citrinos'),
    ('Tabaco'),
    ('Doce'),
    ('Lavanda'),
    ('Rum'),
    ('Amadeirado'),
    ('Caramelo'),
    ('Frutado'),
    ('Couro'),
    ('Mel'),
    ('Atalcado'),
    ('Floral Branco'),
    ('Lactônico'),
    ('Esfumaçado'),
    ('Almiscarado'),
    ('Tropical'),
    ('Musgo'),
    ('Café'),
    ('Especiado Suave'),
    ('Balsâmico'),
    ('Canela'),
    ('Cereja'),
    ('Amendoado'),
    ('Tabaco'),
    ('Patchouli'),
    ('Cacau'),
    ('Tuberosa'),
    ('Animálico'),
    ('Terroso');